input: ["img"]
output: ["bboxes", "bbox_labels", "bbox_scores"]

exp_path: ""
ckpt_file: ""
voc_classes: {   # the values in voc_classes are called in the following custom nodes: draw.bbox, draw.score, output.smart_notification
        0: "no ppe",
        1: "all ppe",
        2: "no mask & vest",
        3: "no helmet & vest",
        4: "no helmet & mask",
        5: "no helmet",
        6: "no vest",
        7: "no mask",
}
device: "gpu"
fp16: false
confthre: ""
nmsthre: ""
